language: python
python: "2.7"
dist: xenial
sudo: required
cache:
  directories:
    - eggs
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
  exclude:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
  allow_failures:
    - env: PLONE_VERSION=5.2.x
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - pip install -r requirements.txt
  - buildout -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/test-coverage
  - pip install -q coveralls
  - coveralls
